name: pg_management
description: A complete role-based PG management platform.
publish_to: "none"
version: 1.8.0+9

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^1.2.3
  intl: ^0.20.2
  package_info_plus: ^10.2.0
  pdf: ^3.13.0
  printing: ^5.15.0
  share_plus: ^13.2.0
  shared_preferences: ^2.3.2
  supabase_flutter: ^2.15.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#1A7F72"
  adaptive_icon_foreground: "assets/icon/app_icon_fg.png"

flutter:
  uses-material-design: true
