import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

// The PDF base fonts have no ₹ glyph, so amounts use "Rs." here.
String _rs(num value) =>
    NumberFormat.currency(locale: 'en_IN', symbol: 'Rs. ', decimalDigits: 0)
        .format(value);

Future<Uint8List> buildReceiptPdf({
  required String pgName,
  required String ref,
  required int amount,
  required List<(String, String)> rows,
}) async {
  const teal = PdfColor.fromInt(0xFF1A7F72);
  const grey = PdfColor.fromInt(0xFF6B7570);
  final doc = pw.Document(title: ref);
  doc.addPage(pw.Page(
    pageFormat: PdfPageFormat.a5,
    build: (context) => pw.Padding(
      padding: const pw.EdgeInsets.all(28),
      child:
          pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
        pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
          pw.Text('PG Management',
              style: const pw.TextStyle(
                  fontSize: 18, fontWeight: pw.FontWeight.bold, color: teal)),
          pw.Text('PAYMENT RECEIPT',
              style: const pw.TextStyle(fontSize: 10, color: grey)),
        ]),
        pw.SizedBox(height: 4),
        pw.Text('$pgName · Receipt $ref',
            style: const pw.TextStyle(fontSize: 10, color: grey)),
        pw.Divider(color: grey, height: 24),
        ...rows.map((row) => pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 5),
              child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(row.$1,
                        style: const pw.TextStyle(fontSize: 11, color: grey)),
                    pw.Text(row.$2,
                        style: const pw.TextStyle(
                            fontSize: 11, fontWeight: pw.FontWeight.bold)),
                  ]),
            )),
        pw.Divider(color: grey, height: 24),
        pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
          pw.Text('TOTAL PAID',
              style: const pw.TextStyle(
                  fontSize: 12, fontWeight: pw.FontWeight.bold)),
          pw.Text(_rs(amount),
              style: const pw.TextStyle(
                  fontSize: 18, fontWeight: pw.FontWeight.bold, color: teal)),
        ]),
        pw.Spacer(),
        pw.Text(
            'Generated by PG Management · demo receipt, not a tax document.',
            style: const pw.TextStyle(fontSize: 8, color: grey)),
      ]),
    ),
  ));
  return doc.save();
}

/// Opens the platform share sheet (mobile) or downloads the file (web).
Future<void> shareReceiptPdf(Uint8List bytes, String filename) =>
    Printing.sharePdf(bytes: bytes, filename: filename);

/// Opens the print/save-as-PDF dialog.
Future<void> printReceiptPdf(Uint8List bytes, String name) =>
    Printing.layoutPdf(onLayout: (_) async => bytes, name: name);
